CREATE TABLE EK_MENU (
M_NO NUMBER (3) PRIMARY KEY,
M_NAME VARCHAR2(20 CHAR) UNIQUE NOT NULL, 
M_PRICE NUMBER(5) NOT NULL, 
M_IMG VARCHAR2(20 CHAR) NOT NULL, 
M_ICE NUMBER(1) NOT NULL, 
M_TYPE VARCHAR2(20 CHAR) NOT NULL, 
M_TYPE_EASY VARCHAR2(20 CHAR) NOT NULL,
M_WEATHER NUMBER(1), 
M_STOCK NUMBER(1) NOT NULL 
);

create sequence EK_MENU_seq;

select * from EK_MENU where M_TYPE = 'COFFEE';

select * from EK_MENU;

INSERT INTO EK_MENU VALUES (EK_MENU_SEQ.NEXTVAL, '아메리카노', 3000, 'TEST.IMG', 2, 'COFFEE', 'COFFEE', 0, 1);
INSERT INTO EK_MENU VALUES (EK_MENU_SEQ.NEXTVAL, '카푸치노', 5000, 'TEST.IMG', 2, 'COFFEE', 'COFFEE', 0, 0);
INSERT INTO EK_MENU VALUES (EK_MENU_SEQ.NEXTVAL, '밀크티', 4000, 'TEST.IMG', 2, 'TEA', 'TEA', 0, 1);
INSERT INTO EK_MENU VALUES (EK_MENU_SEQ.NEXTVAL, '자몽 네이블오렌지', 7000, 'TEST.IMG', 2, 'TEA', 'NONE', 0, 0);
INSERT INTO EK_MENU VALUES (EK_MENU_SEQ.NEXTVAL, '연유 카페라떼', 6000, 'TEST.IMG', 2, 'BEVERAGE', 'BEVERAGE', 0, 1);
INSERT INTO EK_MENU VALUES (EK_MENU_SEQ.NEXTVAL, '토피넛 라떼', 5500, 'TEST.IMG', 2, 'BEVERAGE', 'NONE', 0, 0);


INSERT INTO EK_MENU VALUES (EK_MENU_SEQ.NEXTVAL, '에스프레소', 4000, 'TEST.IMG', 0, 'COFFEE', 'COFFEE', 2, 1);
INSERT INTO EK_MENU VALUES (EK_MENU_SEQ.NEXTVAL, '에스프레소 마끼아또', 6000, 'TEST.IMG', 0, 'COFFEE', 'COFFEE', 2, 0);
INSERT INTO EK_MENU VALUES (EK_MENU_SEQ.NEXTVAL, '자몽차', 5000, 'TEST.IMG', 0, 'TEA', 'TEA', 1, 1);
INSERT INTO EK_MENU VALUES (EK_MENU_SEQ.NEXTVAL, '석류', 7000, 'TEST.IMG', 0, 'TEA', 'NONE', 1, 0);

INSERT INTO EK_MENU VALUES (EK_MENU_SEQ.NEXTVAL, '콜드브루', 5000, 'TEST.IMG', 1, 'COFFEE', 'COFFEE', 1, 1);
INSERT INTO EK_MENU VALUES (EK_MENU_SEQ.NEXTVAL, '넛츠 크림 라떼', 7000, 'TEST.IMG', 1, 'COFFEE', 'COFFEE', 1, 0);
INSERT INTO EK_MENU VALUES (EK_MENU_SEQ.NEXTVAL, '레몬 에이드', 5000, 'TEST.IMG', 1, 'SHAKE_ADE', 'BEVERAGE', 0, 1);
INSERT INTO EK_MENU VALUES (EK_MENU_SEQ.NEXTVAL, '오리진 쉐이크', 4500, 'TEST,IMG', 1, 'SHAKE_ADE', 'NONE', 0, 1);

INSERT INTO EK_MENU VALUES (EK_MENU_SEQ.NEXTVAL, '크루아상', 4000, 'TEST.IMG', 1, 'DESSERT', 'DESSERT', 0, 1);
INSERT INTO EK_MENU VALUES (EK_MENU_SEQ.NEXTVAL, '라이스치즈볼 핫 디트로이트 딥소스', 10000, 'TEST.IMG', 1, 'DESSERT', 'NONE', 0, 0);
INSERT INTO EK_MENU VALUES (EK_MENU_SEQ.NEXTVAL, '라이스치즈볼 미소버터 딥소스', 10000, 'TEST.IMG', 1, 'DESSERT', 'NONE', 0, 1);
INSERT INTO EK_MENU VALUES (EK_MENU_SEQ.NEXTVAL, '흑임자 팥붕어빵', 3000, 'TEST.IMG', 1, 'DESSERT', 'DESSERT', 0, 1);
INSERT INTO EK_MENU VALUES (EK_MENU_SEQ.NEXTVAL, '흑임자 슈크림붕어빵', 3000, 'TEST.IMG', 1, 'DESSERT', 'DESSERT', 0, 0);